<?php

defined('BASEPATH') OR exit('No direct script access allowed');

// use namespace
use Restserver\Libraries\REST_Controller;

class Presensi extends Api_Controller {

    public function __construct() {
		// Construct the parent class
        parent::__construct();
                   
    }

    public function index_get() {

        $this->response(array('success' => false), REST_Controller::HTTP_NOT_FOUND); // OK (200) being the HTTP response code
       
    }

    public function index_post() {

        $this->response(array('success' => true), REST_Controller::HTTP_NOT_FOUND); // OK (200) being the HTTP response code

    }

    public function checkinout_post()
    {
        $vtgl = $this->post('tanggal');
        $reqTgl = date('Y-m-d',strtotime($vtgl));

        if ($vtgl==null)
        {
            $this->response([
                'status' => FALSE,
                'message' => 'Cek kembali parameter'
            ], REST_Controller::HTTP_NOT_FOUND);
        } else {
            $this->db->select('userid as nip,checktime');
            $this->db->where('DATE(checktime)', "'".$reqTgl."'", FALSE);
            $dataabsen = $this->db->get("checkinout");
            if ($dataabsen->num_rows() > 0) {
                $this->response([
                    'status' => true,
                    'message' => 'List data presensi',
                    'data' => $dataabsen->result_array()
                ], REST_Controller::HTTP_OK);

            } else {
                $this->response([
                    'status' => FALSE,
                    'message' => 'Tidak ada data cek in'
                ], REST_Controller::HTTP_NOT_FOUND);
            }
        }
    }


    public function ulapeg_post()
    {
        $token = $this->input->post('token');
        $kode_usulan = $this->input->post('kode_usulan');
        $nip = $this->input->post('nip');
        $jenis_cuti = $this->input->post('jenis_cuti');
        $jum_hari = $this->input->post('jum_hari');
        $tmulai = $this->input->post('tmulai');
        $takhir = $this->input->post('takhir');
        $keterangan = $this->input->post('keterangan');
        $keterangan_detail = $this->input->post('keterangan_detail');
        $tgl_input = $this->input->post('tgl_input');

        $this->db->where('api_token', $token);
        $rwo = $this->db->get("api_client");
        if ($rwo->num_rows()>0) {

            $arrint= array(
                'token_api'=>$token,
                'api_method'=>'ulapeg_post',
                'api_ip'=>getRealIpAddr()
            );

            $this->db->insert('api_log',$arrint) ;

            $arrintd= array(
                'kode_usulan'=>$kode_usulan,
                'nip'=>$nip,
                'jenis_cuti'=>$jenis_cuti,
                'jum_hari'=>$jum_hari,
                'tmulai'=>$tmulai,
                'takhir'=>$takhir,
                'keterangan'=>$keterangan,
                'keterangan_detail'=>$keterangan_detail,
                'tgl_input'=>$tgl_input,
            );

            $this->db->insert('ulapeg_detail_cuti',$arrintd) ;

            if ($this->db->affected_rows() != 1) {
                $this->response([
                    'status' => FALSE,
                    'message' => 'Cannot be insert!'
                ], REST_Controller::HTTP_NOT_FOUND);
            } else {
                $message = array(
                    'status' => TRUE, // Automatically generated by the model
                    'message' => 'Has been inserted!'
                );
                $this->set_response($message, REST_Controller::HTTP_OK);
            }


        } else {
            $this->response([
                'status' => FALSE,
                'message' => 'Not Authorize!'
            ], REST_Controller::HTTP_NOT_FOUND);
        }

    }

    public function getpotongan_post()
    {
        $token = $this->input->post('token');
        $nip = $this->input->post('nip');
        $bulan = $this->input->post('month');
        $tahun = $this->input->post('year');

        $msg='';
        if (!is_numeric($bulan)) {
            $msg .='Month';
        }

        if (!is_numeric($tahun)) {
            if (empty($msg)){
                $msg .=' Year';
            } else {
                $msg .=' and Year ';
            }
        }

        if (empty($msg))
        {
            $this->db->where('api_token', $token);
            $rwo = $this->db->get("api_client");
            if ($rwo->num_rows()>0) {

                $arrint= array(
                    'token_api'=>$token,
                    'api_method'=>'getpotongan_post',
                    'api_ip'=>getRealIpAddr()
                );

                $this->db->insert('api_log',$arrint) ;
                $hasil = $this->view1($nip,$bulan,$tahun);
                $message = array(
                    'status' => TRUE, // Automatically generated by the model
                    'results' => $hasil
                );
                $this->set_response($message, REST_Controller::HTTP_OK);

            } else {
                $this->response([
                    'status' => FALSE,
                    'message' => 'Not Authorize!'
                ], REST_Controller::HTTP_NOT_FOUND);
            }
        } else {
            $this->response([
                'status' => FALSE,
                'message' => 'Check your '.$msg.' parameters'
            ], REST_Controller::HTTP_NOT_FOUND);
        }

    }

    function view1($userid,$bulan,$tahun)
    {
        $this->load->model('utils_model','utils');
		$this->load->model('pegawai/pegawai_model','pegawai');
        $this->load->model('report_model');

        $postdatestart = $tahun.'-'.$bulan."-01";
        $postdatestop = date("Y-m-t", strtotime($postdatestart)); //$this->input->post('end');

        //$postdatestart = dmyToymd($this->input->post('start'));
        //$postdatestop = dmyToymd($this->input->post('end'));

        $datestart = strtotime($postdatestart);
        $datestop = strtotime($postdatestop);

        $mastertunj = array();

        //trap referensi data
        //$this->session->set_userdata('tahundata',date("Y",$datestart));
/* 
        $sqlv = "select * from mastertunjangan";
        $validdate = strtotime('01-11-2018');
        if ($datestart < $validdate )
        {
            $sqlv = "select * from mastertunjangan_2018";
        } */
        $nmTble= namaTableTunjangan($postdatestart);
        $sqlv = "select * from ".$nmTble;

        $query = $this->db->query($sqlv);
        foreach ($query->result() as $que) {
            $mastertunj[$que->kelasjabatan] = $que->tunjangan;
        }
        $orgid = array();
        $areaid = array();
        $tbar = array();
        $bbar = array();
        $holar = array();
        $range = ($datestop - $datestart) / 86400;
        $totalworkday = 0; $totalholiday = 0; $totalnonworkingday = 0; $holonnwds = 0;

        $pkrga = array();
        $akrga = array();
        $attrecap = $this->report_model->getatt();
        foreach($attrecap->result() as $at) {
            $atar[$at->atid] = $at->atname;
            $attend[] = array(
                'atid'		=> $at->atid,
                'atname'	=> $at->atname
            );
            $pkrga[$at->atid] = $at->value;
            $akrga[$at->atid] = $at->ign_to;
        }
        $pkrg = array();
        $absrecap = $this->report_model->getabs();
        foreach($absrecap->result() as $bs) {
            $bbar[$bs->abid] = $bs->abname;
            $absen[] = array(
                'abid'		=> $bs->abid,
                'abname'	=> $bs->abname
            );
            $pkrg[$bs->abid] = $bs->value;
        }

        $dept = $this->report_model->getdept();
        foreach($dept->result() as $depat) {
            $deptar[$depat->deptid] = $depat->deptname;
        }

        $queryemp = $this->report_model->getuseremployeedetailsxx($userid);
        $yo=2;

        $aten = array();
        $aben = array();

        $dataallay = array();

        $rslt = $queryemp->result() ;
        foreach($rslt as $queq) {

            $unkir= isset($mastertunj[$queq->kelasjabatan])?$mastertunj[$queq->kelasjabatan]:0;

            $isplt=0;$isViewIt=1;

            //if (date("Y",$datestart)>2016) {
            if (isset($queq->tmt_plt) && isset($queq->plt_deptid) && isset($queq->plt_eselon))
            {
                if ($queq->tmt_plt !='0000-00-00') {
                    //echo $queq->userid." 1<br>";
                    $time = strtotime($queq->tmt_plt);
                    //$final = strtotime("+1 month", $time);
                    //pindah bulan udah dapet plt/plh
                    if ($datestart >= strtotime(date("Y-m-01",$time))) {
                        if ((intval(date('d', $time)) < 6) && date("Y-m", $datestart) === date('Y-m', $time)) {
                            $isplt = 1;
                            //echo $queq->userid." 2<br>";
                        } else {
                            $time2 = strtotime(date('Y-m-01', $time));
                            $final = strtotime("+1 month", $time2);
                            if ($datestart >= $final) {
                                $isplt = 1;
                            } else {
                                if (!in_array($queq->deptid, $orgid))
                                {
                                    continue;
                                }
                            }
                        }
                    } else{
                        $isViewIt=0;
                        //continue;
                        //echo $queq->userid." ".in_array($queq->deptid, $orgid)."<br>";
                        if (!in_array($queq->deptid, $orgid))
                        {
                            continue;
                        }
                    }
                }/*else{
                        echo $queq->userid." 4<br>";
                    }*/
            }
            // }


            $jbtnDef = strval(konversiEselonBaru($queq->eselon));
            $jbtnPlt = strval(konversiEselonBaru($queq->plt_eselon));
            $unkirplt=0;
            $kriteriaPlt = 0;

            if ($isplt==1) {
                $unkirplt= isset($mastertunj[$queq->plt_kelasjabatan]) ? $mastertunj[$queq->plt_kelasjabatan] * refTHP() :0;
                if ( ($jbtnDef  > $jbtnPlt) ) {
                    $kriteriaPlt=1;
                    $unkirplt= isset($mastertunj[$queq->plt_kelasjabatan])?$mastertunj[$queq->plt_kelasjabatan] :0;
                    $unkirplt= ($unkirplt * refTHP() ) * refPLT();
                }
                if ( ($jbtnDef  == $jbtnPlt ) ) {
                    $kriteriaPlt=2;
                    /*$unkirplt= isset($mastertunj[$queq->plt_kelasjabatan])?$mastertunj[$queq->plt_kelasjabatan]:0;
                    $unkirplt= ($unkirplt * refTHP()) * refPLT();*/
                    if ($queq->plt_kelasjabatan > $queq->kelasjabatan) {
                        $unkirplt = isset($mastertunj[$queq->plt_kelasjabatan]) ? $mastertunj[$queq->plt_kelasjabatan] : 0;
                        $unkirplt = ($unkirplt * refTHP());
                        $unkir = ($unkir * refTHP()) * refPLT();
                    } else
                    {
                        $unkirplt = isset($mastertunj[$queq->plt_kelasjabatan]) ? $mastertunj[$queq->plt_kelasjabatan] : 0;
                        $unkirplt = ($unkirplt * refTHP()) * refPLT();
                    }
                }

                if ( ($jbtnDef  < $jbtnPlt ) ) {
                    $kriteriaPlt=3;
                    $klsjbatan = max(array($queq->kelasjabatan,$queq->plt_kelasjabatan));
					$klsjbatan =$queq->plt_kelasjabatan;
                    //$unkirplt= isset($mastertunj[$klsjbatan])?$mastertunj[$klsjbatan] * refTHP() :0;
                    //old
                    $unkirplt= isset($mastertunj[$klsjbatan])?$mastertunj[$klsjbatan]* refTHP() :0;
                    $unkir = 0;
                }
            }

            if ($queq->payable == 0){
                $unkir=0;
                $unkirplt=0;
            }

            //echo $queq->userid.' '.$isplt." ".$kriteriaPlt." ".$queq->userid." ".$unkir." ".$unkirplt." ".$jbtnDef." ".$jbtnPlt."<br>";
            //die();

            $dataallay[] = array(
                'userid'   => $queq->userid,
                'empTitle' => $queq->title,
                'empID' => $queq->badgenumber,
                'empHire' => isset($queq->hireddate)?date('d-m-Y', strtotime($queq->hireddate)):'',
                'empName' => $queq->name,
                'deptName' => isset($deptar[$queq->deptid])?$deptar[$queq->deptid]:'',
                'kelasjabatan' => $queq->kelasjabatan,
                'tunjanganprofesi' => $queq->tunjanganprofesi,
                'tmtprofesi' => $queq->tmtprofesi,
                'tunjangan' => $unkir,
                'jftstatus' => $queq->jftstatus,
                'jenisjabatan' => $queq->jenisjabatan,
                'jenispegawai' => $queq->jenispegawai,
                'kedudukan' => $queq->kedudukan,
                'tmtkedudukan' => $queq->tmtkedudukan,
                'deptid' => $queq->deptid,
                'tunjanganplt' => $unkirplt,
                'plt_deptid' => $queq->plt_deptid,
                'plt_eselon' => $queq->plt_eselon,
                'tmt_plt' => $queq->tmt_plt,
                'payable' => $queq->payable,
                'eselon' => $queq->eselon,
                'plt_jbtn' => $queq->plt_jbtn,
                'plt_sk' => $queq->plt_sk,
                'plt_kelasjabatan' => $queq->plt_kelasjabatan,
                'isplt' =>$isplt,
                'kriteriaPlt' =>$kriteriaPlt,
                'plt_deptname' => isset($deptar[$queq->plt_deptid])?$deptar[$queq->plt_deptid]:'',
                'dipisah'=>0,
                'ishidden'=>0,
                'isViewIt'=>$isViewIt,
                'orgf'=>""
            );

            foreach($attend as $at3) {
                $aten[$queq->userid][$at3['atid']] = 0;
            }
            foreach($absen as $ab3) {
                $aben[$queq->userid][$ab3['abid']] = 0;
            }
        }

        // $compa = $this->report_model->getcompany();
        // $company = array(
        //     'companyname'	=> isset($compa->row()->companyname)?$compa->row()->companyname:'',
        //     'logo'			=> isset($compa->row()->logo)?$compa->row()->logo:'',
        //     'address1'		=> isset($compa->row()->address1)?$compa->row()->address1:'',
        //     'address2'		=> isset($compa->row()->address2)?$compa->row()->address2:'',
        //     'phone'			=> isset($compa->row()->phone)?$compa->row()->phone:'',
        //     'fax'			=> isset($compa->row()->fax)?$compa->row()->fax:''
        // );
        $dataallaye = array();
        $datafoot = array();
        $abc=0;
        $dataview = '';
        $datavw = '';
        $data = array();

        foreach($dataallay as $queqe) {

            $querytempo = $this->report_model->getattlogo($datestart, $datestop, $queqe['userid']);
            $querytemp = $this->report_model->getattlog($datestart, $datestop, $queqe['userid']);

            $dataarray = array();
            $totallate=0; $totalearly=0; $totalotbef=0; $totalotaf=0; $total=0;
            $totallater=0; $totalearlyr=0; $totalotr=0; $totalr=0; $workinholiday=0; $attendance=0; $absence=0; $off=0; $alpha=0;$editcome=0;$edithome=0;$workday=0;
            $totallibur  = 0; $tubel = 0; $totaltubel = 0; $totaltubelplt=0;$tunjtubel = 0; $tunjtubelplt = 0; $tgltubel = 0;
            $totalpersensemua = 0; $totalalpa = 0; $totalmasuk = 0; $totalpembatalan = 0; $totaljadwal=0; $totalblnk=0; $totalsemua = 0;
            $tunbul = array(); $tunbuli = 0; $tottun = 0; $tunj = 0; $totplt = 0;$tunjplt = 0;
            $ttlmsk = array(); $tunjangan = array(); $tunjanganplt = array();$tunbulplt = array();
            $tunprobul = array(); $tunpro = 0; $tunjanganpro = array();
            $jft = array(); $jfto = 0; $jftp = array();
            $jpeg = array(); $jpego = 0; $jpegp = array();
            $kedu = array(); $keduo = 0; $kedup = array();
            $totaltunjplt =array();$totaltunj =array();

            foreach($querytempo->result() as $que) {
                $ttlmsk[date('mY', strtotime($que->date_shift))] = 0;
                $totaltunj[date('mY', strtotime($que->date_shift))] = 0;
                $totaltunjplt[date('mY', strtotime($que->date_shift))] = 0;
            }

            foreach($querytempo->result() as $que) {

                $kelas = $this->report_model->getkelasjabatan($queqe['userid'], $que->date_shift);
                if ($kelas != 0) $queqe['kelasjabatan'] = $kelas;
                $tunjang = $this->report_model->gettunjang($que->date_shift, $queqe['kelasjabatan']);
                if ($tunjang == 0) $tunjang = $mastertunj[$queqe['kelasjabatan']];
                //echo $tunjang;
                if($tunjang!=0) {
                    $queqe['tunjanganasli']=$tunjang;
                    if ($queqe['userid'] != 0 ) {
                        //if (date("Y", $datestart) > 2016) {
                        $queqe['tunjangan'] = $tunjang * refTHP();
                        /*} else {
                            $queqe['tunjangan'] = $tunjang;
                        }*/
                    } else {
                        $queqe['tunjangan'] = 0;
                    }
                    //baru
                    if ($queqe['kriteriaPlt']==2)
                    {
                        if ( $queqe['plt_kelasjabatan'] > $queqe['kelasjabatan']) {
                            $tjngnga = isset($mastertunj[$queqe['kelasjabatan']]) ? $mastertunj[$queqe['kelasjabatan']] : 0;
                            $queqe['tunjangan'] = ($tjngnga * refTHP()) * refPLT();
                        } else
                        {
                            $tjngnga = isset($mastertunj[$queqe['kelasjabatan']]) ? $mastertunj[$queqe['kelasjabatan']] : 0;
                            $queqe['tunjangan'] = $tjngnga * refTHP();
                        }
                    }
                }

                if($que->attendance != 'NWK' &&
                    $que->attendance != 'NWDS' &&
                    $que->workinholiday != 1)
                    $ttlmsk[date('mY', strtotime($que->date_shift))]++;

                if($que->flaghol == 1)
                    $ttlmsk[date('mY', strtotime($que->date_shift))]++;

                if($tunbuli!=$queqe['tunjangan']) {
                    $kali = ($queqe['kedudukan']==4 && ($datestart >= strtotime(date("Y-m-01",strtotime($queqe['tmtkedudukan'])))))? 1 : 1; //0.5 : 1
                    $tunbul[date('mY', strtotime($que->date_shift))][date('j', strtotime($que->date_shift))] = $queqe['tunjangan'] * $kali;
                    $tunbulplt[date('mY', strtotime($que->date_shift))][date('j', strtotime($que->date_shift))] = $queqe['tunjanganplt'];
                }

                //echo $que->date_shift." ".$queqe['tunjangan']."<br>";

                $byuser= $userid!='undefined'?1:0;
                if ($byuser==0) {
                    if ($queqe['kriteriaPlt'] == 3)
                    {
                        $pltdepid = strlen($queqe['plt_deptid'])==7 ? "0".$queqe['plt_deptid']: $queqe['plt_deptid'];
                        $cpltdeptid =isOrgIn($pltdepid);

                        $orgtar = strlen($this->input->post('org'))==7 ? "0".$this->input->post('org'): $this->input->post('org');
                        $corgtar  = isOrgIn($orgtar);

                        //asalnya tidak sama
                        /*if ($cpltdeptid === $corgtar)
                        {
                            $queqe['ishidden'] = 0;
                        }*/
                        $queqe['ishidden'] = ($cpltdeptid != $corgtar)?1:0;
                        //echo $queqe['userid']." ".$cpltdeptid." ".$corgtar." ".$queqe['ishidden']."<br>";
                    }
                }

                if ($byuser==0)
                {
                    if ($queqe['kriteriaPlt'] == 1 || $queqe['kriteriaPlt'] == 2) {
                        if($this->input->post('org')!='undefined')
                        {
                            $pltdepid = strlen($queqe['plt_deptid'])==7 ? "0".$queqe['plt_deptid']: $queqe['plt_deptid'];
                            $cpltdeptid =isOrgIn($pltdepid);

                            $depid = strlen($queqe['deptid'])==7 ? "0".$queqe['deptid']: $queqe['deptid'];
                            $cdeptid =isOrgIn($depid);

                            $dibagi = ($cpltdeptid == $cdeptid) ? 0 : 1;

                            $orgtar = strlen($this->input->post('org'))==7 ? "0".$this->input->post('org'): $this->input->post('org');
                            $corgtar  = isOrgIn($orgtar);
                            if ($dibagi==1)
                            {
                                if ($cdeptid == $corgtar) //satu tempat defenitif
                                {
                                    $queqe['dipisah']= 1;
                                }
                                if ($cpltdeptid == $corgtar) //satu tempat plt/plh
                                {
                                    $queqe['dipisah']= 2;
                                }
                            }

                            if ($tunbuli != $queqe['tunjangan']) {
                                $kali = ($queqe['kedudukan']==4 && ($datestart >= strtotime(date("Y-m-01",strtotime($queqe['tmtkedudukan']))))) ? 1 : 1; //0.5 : 1
                                $tunbul[date('mY', strtotime($que->date_shift))][date('j', strtotime($que->date_shift))] = $queqe['tunjangan'] * $kali;
                                $tunbulplt[date('mY', strtotime($que->date_shift))][date('j', strtotime($que->date_shift))] = $queqe['tunjanganplt'] * $kali;
                            }
                        }
                    }

                    if ($queqe['kriteriaPlt'] == 3) {
                        $pltdepid = strlen($queqe['plt_deptid'])==7 ? "0".$queqe['plt_deptid']: $queqe['plt_deptid'];
                        $cpltdeptid =isOrgIn($pltdepid);

                        $depid = strlen($queqe['deptid'])==7 ? "0".$queqe['deptid']: $queqe['deptid'];
                        $cdeptid = isOrgIn($depid);

                        $dibagi = ($cpltdeptid == $cdeptid) ? 0 : 1;

                        $orgtar = strlen($this->input->post('org'))==7 ? "0".$this->input->post('org'): $this->input->post('org');
                        $corgtar  = isOrgIn($orgtar);

                        if ($dibagi==1)
                        {
                            if ($cdeptid == $corgtar) //satu tempat defenitif
                            {
                                $queqe['dipisah']= 1;
                            }
                            if ($cpltdeptid == $corgtar) //satu tempat plt/plh
                            {
                                $queqe['dipisah']= 2;
                            }
                        }
                    }
                } else
                {
                    if ($queqe['kriteriaPlt'] == 1 || $queqe['kriteriaPlt'] == 2) {
                        if($this->input->post('org')!='undefined')
                        {
                            $pltdepid = strlen($queqe['plt_deptid'])==7 ? "0".$queqe['plt_deptid']: $queqe['plt_deptid'];
                            $cpltdeptid =isOrgIn($pltdepid);

                            $depid = strlen($queqe['deptid'])==7 ? "0".$queqe['deptid']: $queqe['deptid'];
                            $cdeptid =isOrgIn($depid);

                            $dibagi = ($cpltdeptid == $cdeptid) ? 0 : 1;

                            $orgtar = strlen($this->input->post('org'))==7 ? "0".$this->input->post('org'): $this->input->post('org');
                            $corgtar  =isOrgIn($orgtar);

                            $queqe['orgf']= $cdeptid." ".$cpltdeptid.' '.$corgtar;
                            if ($dibagi)
                            {
                                if ($cdeptid === $corgtar) //satu tempat defenitif
                                {
                                    $queqe['dipisah']= 1;
                                }
                                if ($cpltdeptid === $corgtar) //satu tempat plt/plh
                                {
                                    $queqe['dipisah']= 2;
                                }
                            }
                            if ($tunbuli != $queqe['tunjangan']) {
                                $kali = ($queqe['kedudukan']==4 && ($datestart >= strtotime(date("Y-m-01",strtotime($queqe['tmtkedudukan']))))) ? 1 : 1; //0.5 : 1
                                $tunbul[date('mY', strtotime($que->date_shift))][date('j', strtotime($que->date_shift))] = $queqe['tunjangan'] * $kali;
                                $tunbulplt[date('mY', strtotime($que->date_shift))][date('j', strtotime($que->date_shift))] = $queqe['tunjanganplt'] * $kali;
                            }
                        }
                    }

                    if ($queqe['kriteriaPlt'] == 3) {
                        $pltdepid = strlen($queqe['plt_deptid'])==7 ? "0".$queqe['plt_deptid']: $queqe['plt_deptid'];
                        $cpltdeptid =isOrgIn($pltdepid);

                        $depid = strlen($queqe['deptid'])==7 ? "0".$queqe['deptid']: $queqe['deptid'];
                        $cdeptid = isOrgIn($depid);

                        $dibagi = ($cpltdeptid == $cdeptid) ? 0 : 1;

                        $orgtar = strlen($this->input->post('org'))==7 ? "0".$this->input->post('org'): $this->input->post('org');
                        $corgtar  =  isOrgIn($orgtar);
                        if ($dibagi)
                        {
                            if ($cdeptid == $corgtar) //satu tempat defenitif
                            {
                                $queqe['dipisah']= 1;
                            }
                            if ($cpltdeptid == $corgtar) //satu tempat plt/plh
                            {
                                $queqe['dipisah']= 2;
                            }
                        }
                    }
                }

                //else
                //	$tunbul[date('mY', strtotime($que->date_shift))][1] = $queqe['tunjangan'];
                $jftpeg = $this->report_model->getjenispeghis($queqe['userid'], $que->date_shift, 1);
                if($jftpeg!=0) $queqe['jftstatus'] = $jftpeg;

                if($jfto!=$queqe['jftstatus'])
                    $jft[date('mY', strtotime($que->date_shift))][date('j', strtotime($que->date_shift))] = $queqe['jftstatus'];
                /* else
                    $jft[date('mY', strtotime($que->date_shift))][1] = $queqe['jftstatus']; */

                $jpegpeg = $this->report_model->getjenispeghis($queqe['userid'], $que->date_shift, 2);
                if($jpegpeg!=0) $queqe['jenispegawai'] = $jpegpeg;

                if($jpego!=$queqe['jenispegawai'])
                    $jpeg[date('mY', strtotime($que->date_shift))][date('j', strtotime($que->date_shift))] = $queqe['jenispegawai'];
                /* else
                    $jpeg[date('mY', strtotime($que->date_shift))][1] = $queqe['jenispegawai']; */

                $kedupeg = $this->report_model->getjenispeghis($queqe['userid'], $que->date_shift, 3);
                if($kedupeg!=0) $queqe['kedudukan'] = $kedupeg;

                if($keduo!=$queqe['kedudukan'])
                    $kedu[date('mY', strtotime($que->date_shift))][date('j', strtotime($que->date_shift))] = $queqe['kedudukan'];
                /* else
                    $kedu[date('mY', strtotime($que->date_shift))][1] = $queqe['kedudukan']; */

                $tunjangprof = $this->report_model->gettunjangprof($queqe['userid'], $que->date_shift);
                //if($tunjangprof!=0) $queqe['tunjanganprofesi'] = $tunjangprof;
                if($tunjangprof!=0) {
                    if (strtotime($que->date_shift)>=strtotime($queqe['tmtprofesi']))
                    {
                        $queqe['tunjanganprofesi'] = $tunjangprof;
                    } else {
                        $queqe['tunjanganprofesi']=0;
                    }
                }

                //if($tunpro!=$queqe['tunjanganprofesi'])
                //    $tunprobul[date('mY', strtotime($que->date_shift))][date('j', strtotime($que->date_shift))] = $queqe['tunjanganprofesi'];

                if($tunpro!=$queqe['tunjanganprofesi']) {
                    //if (date("Y", $datestart) > 2016) {
                    if (strtotime($que->date_shift)>=strtotime($queqe['tmtprofesi'])) {
                        $tunprobul[date('mY', strtotime($que->date_shift))][date('j', strtotime($que->date_shift))] = $queqe['tunjanganprofesi'] ; //* 0.5
                    } else {
                        $tunprobul[date('mY', strtotime($que->date_shift))][date('j', strtotime($que->date_shift))] = 0;
                    }

                    /*} else {
                        $tunprobul[date('mY', strtotime($que->date_shift))][date('j', strtotime($que->date_shift))] = $queqe['tunjanganprofesi'];

                    }*/
                }

                /* else
                    $tunprobul[date('mY', strtotime($que->date_shift))][1] = $queqe['tunjanganprofesi']; */
                $kali = ($queqe['kedudukan']==4 && ($datestart >= strtotime(date("Y-m-01",strtotime($queqe['tmtkedudukan'])))))? 1 : 1; //0.5
                $tunbuli = $queqe['tunjangan'] * $kali;
                if (strtotime($que->date_shift)>=strtotime($queqe['tmtprofesi'])) {
                    $tunpro = $queqe['tunjanganprofesi'];
                } else{
                    $tunpro = 0;
                }
                $jfto = $queqe['jftstatus'];
                $jpego = $queqe['jenispegawai'];
                $keduo = $queqe['kedudukan'];
                //echo $queqe['jftstatus']."<br>";
                //die();

            }

            foreach($querytemp->result() as $que) {
                $late=0;$early=0;$telat=0;$krglate=0;$krgearly=0;$krgalpa=0;$krgstatus=0;
                $totalpersenkurang = 0; $totaljadwal++;
                $day = date('D', strtotime($que->date_shift));
                $date_in = null; $check_in = null; $break_out = null; $break_in = null; $date_out = null; $check_out = null;
                if(isset($que->check_in)) $check_in = date('H:i:s', strtotime($date_in.' '.$que->check_in));
                if(isset($que->check_out)) $check_out = date('H:i:s', strtotime($date_out.' '.$que->check_out));

                if(isset($tunbul[date('mY', strtotime($que->date_shift))])) {
                    if(isset($tunbul[date('mY', strtotime($que->date_shift))][date('j', strtotime($que->date_shift))])) {
                        $tunjangan[date('mY', strtotime($que->date_shift))] = $tunbul[date('mY', strtotime($que->date_shift))][date('j', strtotime($que->date_shift))] / $ttlmsk[date('mY', strtotime($que->date_shift))];
                        $tunjtubel = $tunbul[date('mY', strtotime($que->date_shift))][date('j', strtotime($que->date_shift))];
                        //echo $tunbul[date('mY', strtotime($que->date_shift))][date('j', strtotime($que->date_shift))];
                        $tunjanganplt[date('mY', strtotime($que->date_shift))] = $tunbulplt[date('mY', strtotime($que->date_shift))][date('j', strtotime($que->date_shift))] / $ttlmsk[date('mY', strtotime($que->date_shift))];
                        $tunjtubelplt = $tunbulplt[date('mY', strtotime($que->date_shift))][date('j', strtotime($que->date_shift))];
                    }
                } else {
                    $tunjangan[date('mY', strtotime($que->date_shift))] = 0;
                    $tunjanganplt[date('mY', strtotime($que->date_shift))] = 0;
                    //echo "1";
                }

                if($queqe['kedudukan']==2 || $queqe['kedudukan']==6 || $queqe['kedudukan']==12) { $tottun = 0;$totplt=0;}
                if($queqe['jenispegawai']==3 || $queqe['jenispegawai']==4) { $tottun = 0;$totplt=0;}

                if(isset($jft[date('mY', strtotime($que->date_shift))][date('j', strtotime($que->date_shift))])) {
                    if($jft[date('mY', strtotime($que->date_shift))][date('j', strtotime($que->date_shift))] != 2) {
                        $tunjangan[date('mY', strtotime($que->date_shift))] = 0;
                        $tunjanganplt[date('mY', strtotime($que->date_shift))] = 0;
                        //echo "1";
                    }
                }

                if(isset($kedu[date('mY', strtotime($que->date_shift))][date('j', strtotime($que->date_shift))])) {
                    if($kedu[date('mY', strtotime($que->date_shift))][date('j', strtotime($que->date_shift))] == 5 ||
                        $kedu[date('mY', strtotime($que->date_shift))][date('j', strtotime($que->date_shift))] == 4) {
                        if ($datestart >= strtotime(date("Y-m-01",strtotime($queqe['tmtkedudukan'])))) {
                            $tunjangan[date('mY', strtotime($que->date_shift))] = $tunjangan[date('mY', strtotime($que->date_shift))] / 2;
                            $tunjanganplt[date('mY', strtotime($que->date_shift))] = $tunjanganplt[date('mY', strtotime($que->date_shift))] / 2;
                        } //else {
                        //$tunjangan[date('mY', strtotime($que->date_shift))] = $tunjangan[date('mY', strtotime($que->date_shift))];
                        // $tunjanganplt[date('mY', strtotime($que->date_shift))] = $tunjanganplt[date('mY', strtotime($que->date_shift))];
                        //}
                        //echo "2";
                    }
                    if($kedu[date('mY', strtotime($que->date_shift))][date('j', strtotime($que->date_shift))] == 2 ||
                        $kedu[date('mY', strtotime($que->date_shift))][date('j', strtotime($que->date_shift))] == 6 ||
                        $kedu[date('mY', strtotime($que->date_shift))][date('j', strtotime($que->date_shift))] == 12) {
                        $tunjangan[date('mY', strtotime($que->date_shift))] = 0;
                        $tunjanganplt[date('mY', strtotime($que->date_shift))] = 0;
                    }
                    if($kedu[date('mY', strtotime($que->date_shift))][date('j', strtotime($que->date_shift))] == 4) {
                        if ($datestart >= strtotime(date("Y-m-01",strtotime($queqe['tmtkedudukan'])))) {
                            $tubel = 1;
                            $tgltubel = strtotime($queqe['tmtkedudukan']);
                        }
                    }
                }

                if(isset($jpeg[date('mY', strtotime($que->date_shift))][date('j', strtotime($que->date_shift))])) {
                    if($jpeg[date('mY', strtotime($que->date_shift))][date('j', strtotime($que->date_shift))] == 3 ||
                        $jpeg[date('mY', strtotime($que->date_shift))][date('j', strtotime($que->date_shift))] == 4) {
                        $tunjangan[date('mY', strtotime($que->date_shift))] = 0;
                        $tunjanganplt[date('mY', strtotime($que->date_shift))] = 0;
                        //echo "3";
                    }
                }

                if(isset($tunprobul[date('mY', strtotime($que->date_shift))][date('j', strtotime($que->date_shift))])) {
                    $tunjanganpro[date('mY', strtotime($que->date_shift))] = $tunprobul[date('mY', strtotime($que->date_shift))][date('j', strtotime($que->date_shift))] / $ttlmsk[date('mY', strtotime($que->date_shift))];
                    if($queqe['tunjanganprofesi']!=null || $queqe['tunjanganprofesi']!=0) {
                        //echo $tunjanganpro[date('mY', strtotime($que->date_shift))]." ".$tunjangan[date('mY', strtotime($que->date_shift))]."<br>";
                        if($tunjanganpro[date('mY', strtotime($que->date_shift))] >= $tunjangan[date('mY', strtotime($que->date_shift))]) {
                            $tunjangan[date('mY', strtotime($que->date_shift))] = 0;
                            $tunjanganplt[date('mY', strtotime($que->date_shift))] = 0;
                            //echo "4";
                        }
                        else {
                            //khusus profesi
                            //$tunjangan[date('mY', strtotime($que->date_shift))] = (($tunjangan[date('mY', strtotime($que->date_shift))]*2) - $tunjanganpro[date('mY', strtotime($que->date_shift))])*refTHP();
                            $tunjangan[date('mY', strtotime($que->date_shift))] = (($tunjangan[date('mY', strtotime($que->date_shift))]) - $tunjanganpro[date('mY', strtotime($que->date_shift))]);
                            $tunjanganplt[date('mY', strtotime($que->date_shift))] = 0;
                            //echo "5";
                        }
                    }
                }
                //echo $queqe['userid'].' '.$tunjangan[date('mY', strtotime($que->date_shift))]." ".$tunjanganpro[date('mY', strtotime($que->date_shift))].'<br>';
                //die();
                //ambil nilai pulang
                $early=0;
                if($que->early_departure!=0) {
                    $early = $que->early_departure;
                }

                if($que->late!=0) {
                    $late = $que->late;

                    if ($que->late >3660) {
                        $telat = $que->late;
                        $late = $telat <= 0 ? 0 : $telat;
                    } else {
                        if ($que->ot_after != 0) {
                            if ($que->ot_after > 3600)
                                $telat = $que->late - 3600;
                            else
                                $telat = $que->late - $que->ot_after;

                            $late = $telat <= 0 ? 0 : $telat;
                        }
                    }

                    if (date("Y",$datestart)<2017)
                    {
                        if($late < 1860) $krglate = 0; //kurang dari 30 menit
                        else if($late >= 1860 && $late < 3660) $krglate = 0.5; //31- 61 menit
                        else if($late >= 3660 && $late < 5460) $krglate = 1; //61- 91 menit
                        else if($late >= 5460) $krglate = 1.5; //91 menit ke atas
                    } else
                    {
                        if($late < 3660) { // < 61 menit
                            $krglate = 0.5;
                            if ($early>=$late) $krglate = 0;
                            if ($check_out == null) $krglate = 0.5;
                        }
                        else if($late >= 3660) { // >=61 menit ke atas
                            $telat = $que->late;
                            $krglate = 1;
                        }

                        //echo $telat." ".$krglate."<br>";
                        //jika terlambat >60 dan mengganti 60 menit
                        if ($que->late > 3660 ) {
                            $krglate = 1;
                            $telat = $que->late;
                        }

                        //berdasarkan referensi potongan untuk terlambat
                        $wry="select persentase FROM ref_potongan WHERE $late BETWEEN rng_menit_1*60 AND rng_menit_2*60 AND jns_potongan=1";
                        $qryPotongan = $this->db->query($wry);
                        if ($qryPotongan->num_rows()>0) {
                            $krglate = $qryPotongan->row()->persentase;
                            //$krglate = 0.5;
                            if ($early>=$late) $krglate = 0;
                            if ($check_out == null) $krglate = $qryPotongan->row()->persentase;
                        }
                    }
                }

                if($que->early_departure!=0) {
                    $early = $que->early_departure;

                    //if (date("Y",$datestart)>2016) {
                    if ($early < 3660) $krgearly = 0.5; else if ($early >= 3660) $krgearly = 1;

                    //potongan PSW
                    $wry="select persentase FROM ref_potongan WHERE $early BETWEEN rng_menit_1*60 AND rng_menit_2*60 AND jns_potongan=2";
                    $qryPotongan = $this->db->query($wry);
                    if ($qryPotongan->num_rows()>0) {
                        $krgearly = $qryPotongan->row()->persentase;
                    }
                    /*} else {
                        if($early > 1 && $early < 1860) $krgearly = 0.5;
                        else if($early >= 1860 && $early < 3660) $krgearly = 1;
                        else if($early >= 3660 && $early < 5460) $krgearly = 1.25;
                        else if($early >= 5460) $krgearly = 1.5;
                    }*/
                }

                //if (date("Y",$datestart)>2016) {
                if ($check_in == null) $krglate = 1;
                if ($check_out == null) $krgearly = 1;
                /*} else {
                    if($check_in==null) $krglate = 1.5;
                    if($check_out==null) $krgearly = 1.5;
                }*/
                if($que->attendance == 'ALP') {
                    $krglate = 0;
                    $krgearly = 0;
                    //if (date("Y",$datestart)>2016) {
                    $krgalpa = 5;
                    /*} else {
                        $krgalpa = 3;
                    }*/
                }

                if($que->attendance == 'BLNK') {
                    $totalblnk++;
                }

                $s = 0;
                if(isset($bbar[$que->attendance])) {
                    $krglate = 0;
                    $krgearly = 0;
                    $krgalpa = 0;
                    $krgstatus = $pkrg[$que->attendance];
                    $s = 1;
                }

                if(isset($atar[$que->attendance])) {
                    if($que->attendance=='AT_SK01' || $que->attendance=='AT_AT1')
                        $krglate = 0;
                    else if($que->attendance=='AT_SK03' || $que->attendance=='AT_AT2')
                        $krgearly = 0;
                    else {
                        $krglate = 0;
                        $krgearly = 0;
                    }
                    $krgalpa = 0;
                    $krgstatus = $pkrga[$que->attendance];

                    switch ($akrga[$que->attendance])
                    {
                        case 1:
                            $krglate = 0;
                            break;
                        case 2:
                            $krgearly = 0;
                            break;
                        default:
                            $krglate = 0;
                            $krgearly = 0;
                            break;
                    }

                }

                if($krglate > 0 && $que->attendance!='NWK' &&
                    $que->attendance!='NWDS' &&
                    $que->workinholiday!=1 ) {
                    $dataarray[] = array(
                        // 'day'			=> $day,
                        'date'			=> date('Y-m-d', strtotime($que->date_shift)),
                        'status'		=> $que->check_in!=null?'Terlambat':'Tidak absen datang',
                        'nilai'			=> $que->check_in==null?null:$this->report_model->itungan($late),
                        'pengurangan'	=> $krglate,
                        'total'			=> ($krglate /100) * ($tunjangan[date('mY', strtotime($que->date_shift))] * $ttlmsk[date('mY', strtotime($que->date_shift))]),
                        'totalplt'	    => ($krglate /100) * ($tunjanganplt[date('mY', strtotime($que->date_shift))] * $ttlmsk[date('mY', strtotime($que->date_shift))])
                    );
                    $totalpersenkurang = $totalpersenkurang + $krglate;
                    $tunj = $tunj + (($krglate /100) * ($tunjangan[date('mY', strtotime($que->date_shift))] * $ttlmsk[date('mY', strtotime($que->date_shift))]));
                    $totallate = $totallate +(($krglate /100) * ($tunjangan[date('mY', strtotime($que->date_shift))] * $ttlmsk[date('mY', strtotime($que->date_shift))]));
                    $tunjplt = $tunjplt + (($krglate /100) * ($tunjanganplt[date('mY', strtotime($que->date_shift))] * $ttlmsk[date('mY', strtotime($que->date_shift))]));
                }

                if($krgearly > 0 && $que->attendance!='NWK' &&
                    $que->attendance!='NWDS' && $que->workinholiday!=1 ) {
                    $dataarray[] = array(
                        // 'day'			=> $day,
                        'date'			=> date('Y-m-d', strtotime($que->date_shift)),
                        'status'		=> $que->check_out!=null?'Pulang lebih awal':'Tidak absen pulang',
                        'nilai'			=> $que->check_out==null?null:$this->report_model->itungan($que->early_departure),
                        'pengurangan'	=> $krgearly,
                        'total'			=> ($krgearly /100) * ($tunjangan[date('mY', strtotime($que->date_shift))] * $ttlmsk[date('mY', strtotime($que->date_shift))]),
                        'totalplt'			=> ($krgearly /100) * ($tunjanganplt[date('mY', strtotime($que->date_shift))] * $ttlmsk[date('mY', strtotime($que->date_shift))])
                    );
                    $totalpersenkurang = $totalpersenkurang + $krgearly;
                    $tunj = $tunj + (($krgearly /100) * ($tunjangan[date('mY', strtotime($que->date_shift))] * $ttlmsk[date('mY', strtotime($que->date_shift))]));
                    $tunjplt = $tunjplt + (($krgearly /100) * ($tunjanganplt[date('mY', strtotime($que->date_shift))] * $ttlmsk[date('mY', strtotime($que->date_shift))]));
                }
                if($krgalpa != 0 && $que->workinholiday!=1) {
                    $dataarray[] = array(
                        // 'day'			=> $day,
                        'date'			=> date('Y-m-d', strtotime($que->date_shift)),
                        'status'		=> 'Alpa',
                        'nilai'			=> null,
                        'pengurangan'	=> $krgalpa,
                        'total'			=> ($krgalpa /100) * ($tunjangan[date('mY', strtotime($que->date_shift))] * $ttlmsk[date('mY', strtotime($que->date_shift))]),
                        'totalplt'			=> ($krgalpa /100) * ($tunjanganplt[date('mY', strtotime($que->date_shift))] * $ttlmsk[date('mY', strtotime($que->date_shift))])
                    );
                    $totalpersenkurang = $totalpersenkurang + $krgalpa;
                    $totalalpa++;
                    $tunj = $tunj + (($krgalpa /100) * ($tunjangan[date('mY', strtotime($que->date_shift))] * $ttlmsk[date('mY', strtotime($que->date_shift))]));
                    $tunjplt = $tunjplt + (($krgalpa /100) * ($tunjanganplt[date('mY', strtotime($que->date_shift))] * $ttlmsk[date('mY', strtotime($que->date_shift))]));
                }
                //echo $totaltubel."<br>TB";
                if($krgstatus != 0  && $queqe['payable']!=0) {
                    $dataarray[] = array(
                        // 'day'			=> $day,
                        'date'			=> date('Y-m-d', strtotime($que->date_shift)),
                        'status'		=> $s==1?$bbar[$que->attendance]:$atar[$que->attendance],
                        'nilai'			=> null,
                        'pengurangan'	=> $krgstatus,
                        'total'			=> ($krgstatus /100) * ($tunjangan[date('mY', strtotime($que->date_shift))] * $ttlmsk[date('mY', strtotime($que->date_shift))]),
                        'totalplt'		=> ($krgstatus /100) * ($tunjanganplt[date('mY', strtotime($que->date_shift))] * $ttlmsk[date('mY', strtotime($que->date_shift))])
                    );

                    $totalpersenkurang = $totalpersenkurang + $krgstatus;
                    if($que->attendance=='AB_12') $totalpembatalan++;
                    $tunj = $tunj + (($krgstatus /100) * ($tunjangan[date('mY', strtotime($que->date_shift))] * $ttlmsk[date('mY', strtotime($que->date_shift))]));
                    $tunjplt = $tunjplt + (($krgstatus /100) * ($tunjanganplt[date('mY', strtotime($que->date_shift))] * $ttlmsk[date('mY', strtotime($que->date_shift))]));
                }

                /*  khusus upacara status dibayarkan
                    tgl upacara,tgl check in kosong dan bukan Tubel
                */
                if (isset($que->date_shift2) && !isset($que->date_in2) && 
                    !isset($que->check_in2) && $queqe['payable'] !=0  && $tubel==0)
                {
                    if(substr($que->attendance,0,2)!='AB') //jika bukan status ketidak hadiran
                    {
                        $nkurang = refUpacara();
                        $dataarray[] = array(
                            // 'day'			=> $day,
                            'date'			=> date('Y-m-d', strtotime($que->date_shift)),
                            'status'		=> 'Tidak mengikuti Upacara',
                            'nilai'			=> null,
                            'pengurangan'	=> $nkurang,
                            'total'			=> ($nkurang/100) * ($tunjangan[date('mY', strtotime($que->date_shift))] * $ttlmsk[date('mY', strtotime($que->date_shift))]),
                            'totalplt'		=> ($nkurang/100) * ($tunjanganplt[date('mY', strtotime($que->date_shift))] * $ttlmsk[date('mY', strtotime($que->date_shift))])
                        );
                        $totalpersenkurang = $totalpersenkurang + $nkurang;
                        $tunj = $tunj + (($nkurang/100) * ($tunjangan[date('mY', strtotime($que->date_shift))] * $ttlmsk[date('mY', strtotime($que->date_shift))]));
                        $tunjplt = $tunjplt + (($nkurang/100) * ($tunjanganplt[date('mY', strtotime($que->date_shift))] * $ttlmsk[date('mY', strtotime($que->date_shift))]));
                    }
                }

                $totalpersensemua = $totalpersensemua + $totalpersenkurang;
                $totalmasuk = array_sum($ttlmsk);

                if($que->attendance != 'NWK' && $que->attendance != 'NWDS' && $que->workinholiday != 1 ) {
                    if($tubel==1) {
                        //$totaltubel = $totaltubel + $tunjangan[date('mY', strtotime($que->date_shift))];
                        //$totaltubelplt = $totaltubelplt+ $tunjanganplt[date('mY', strtotime($que->date_shift))];
                    } else {
                        $totaltunj[date('mY', strtotime($que->date_shift))] = $totaltunj[date('mY', strtotime($que->date_shift))] + $tunjangan[date('mY', strtotime($que->date_shift))];
                        $totaltunjplt[date('mY', strtotime($que->date_shift))] = $totaltunjplt[date('mY', strtotime($que->date_shift))] + $tunjanganplt[date('mY', strtotime($que->date_shift))];
                    }
                }

                if($que->flaghol == 1) {
                    if($tubel==1) {
                        //$totaltubel = $totaltubel + $tunjangan[date('mY', strtotime($que->date_shift))];
                        //$totaltubelplt = $totaltubelplt + $totaltunjplt[date('mY', strtotime($que->date_shift))];
                    } else {
                        $totaltunj[date('mY', strtotime($que->date_shift))] = $totaltunj[date('mY', strtotime($que->date_shift))] + $tunjangan[date('mY', strtotime($que->date_shift))];
                        $totaltunjplt[date('mY', strtotime($que->date_shift))] = $totaltunjplt[date('mY', strtotime($que->date_shift))] + $tunjanganplt[date('mY', strtotime($que->date_shift))];
                    }
                }
                //khususTubel
                if ($tubel==1)
                {
                    if ($que->attendance == 'NWK' || $que->flaghol==1 || $que->attendance=="")
                    {

                    } else
                    {
                        $totaltubel = $totaltubel + $tunjtubel*0.5 ;//$tunjangan[date('mY', strtotime($que->date_shift))];
                        //echo $que->date_shift." ".$que->attendance." ".$tunjtubel*0.5."<br>";
                    }
                }
                //echo $que->date_shift." ".$que->attendance." ".$totaltubel." ".$tunjtubel."<br>";
            }

            //$totaltubel = $totaltubel/$totalmasuk;
            //echo $totalmasuk;
            $tottun = isset($totaltunj)?array_sum($totaltunj):0;
            $totplt = isset($totaltunjplt)?array_sum($totaltunjplt):0;

            //echo $tottun;
            if($tubel==1) {
                $dataarray[] = array(
                    // 'day'			=> '',
                    'date'			=> '',
                    'status'		=> 'Tugas Belajar Per Tgl '.date('d-m-Y', $tgltubel),
                    'nilai'			=> null,
                    'pengurangan'	=> '-',
                    'total'			=> 0,
                    'totalplt'			=> 0
                );
                $tunj = 0;
                $tottun = ($totaltubel/$totalmasuk);
                $totplt= $tunjtubelplt;
            }
            //echo $totaltubel."<br>TB";
            if($totalalpa == $totalmasuk) {
                $tottun = 0;
                $totplt = 0;
            }

            if($totalpembatalan == $totalmasuk) {
                $tottun = 0;
                $totplt = 0;
            }

            $totalsemua = $totalalpa + $totalpembatalan;

            if($totalsemua == $totalmasuk) {
                $tottun = 0;
                $totplt = 0;
            }

            if($totalblnk == $totaljadwal) {
                $tottun = 0;
                $totplt = 0;
            }

            //echo $queqe['userid']." TBL2 ".$tottun." ".$totplt."<br>";
            $dataallaye = array(
                'userid' => $queqe['userid'],
                'jabatan' => $queqe['empTitle'],
                'nama_pegawai' =>$queqe['empName'],
                'nama_satker' => $queqe['deptName'],
                'kelasjabatan' => $queqe['kelasjabatan'],
                'tunjangan' => $tottun,
                'tunjanganplt' => $totplt,
                'plt_sk' => $queqe['plt_sk'],
                'plt_jbtn' => $queqe['plt_jbtn'],
                'plt_kelasjabatan' => $queqe['plt_kelasjabatan'],
                'isplt' => $queqe['isplt'],
                'plt_deptname' => $queqe['plt_deptname'],
                'kriteriaPlt' => $queqe['kriteriaPlt'],
                // 'orgf' => $queqe['orgf']
            );


            $byuser= $userid!='undefined'?1:0;

            $data = array(
                //"dateinfo" => strtoupper(format_date_ind(date('Y-m-d', $datestart) ) ." s/d ".format_date_ind(date('Y-m-d', $datestop))) ,//. " s/d " . date('d-m-Y', $datestop)
                //"index" => $abc,
                // "cominfo" => $company,
                "empinfo" => $dataallaye,
                // "footah" => $datafoot,
                "data" => $dataarray,
                "totaltunj" =>$totaltunj,
                "totaltunjplt" => $totaltunjplt,
                "byuser"=>$byuser,
                "dipisah" =>$queqe['dipisah'],
                // "orgf"=>$queqe['orgf'],
                "ishidden" =>$queqe['ishidden'],
                "isViewIt"=>$queqe['isViewIt']);
            $abc++;
        }
        $result = $this->displaydata($data);
        return $result;
    }

    function displaydata($dataarray)
    {
        $dataresult=null;
        $dataresult['info_pegawai'][] = array(
            'nip'=>$dataarray['empinfo']['userid'],
            'nama_pegawai'=>$dataarray['empinfo']['nama_pegawai'],
            'nama_satker'=>$dataarray['empinfo']['nama_satker'],
            'jabatan'=>$dataarray['empinfo']['jabatan'],
            'kelas_jabatan'=>$dataarray['empinfo']['kelasjabatan'],
            'tunjangan'=>$dataarray['empinfo']['isplt']==0?$dataarray['empinfo']['tunjangan']:$dataarray['empinfo']['tunjanganplt'],
        );
        
        if (!$dataarray['ishidden']) 
        {
            if (($dataarray['empinfo']['tunjangan'] + $dataarray['empinfo']['tunjanganplt']) == 0) 
            {
                //Tidak ada data Tunjangan Kinerja
            } else {
                if (($dataarray['empinfo']['isplt'] == 1)) {

                    $showhunkir = 0;
                    $showhplt = 0;
                    if ($dataarray['empinfo']['kriteriaPlt'] == 1 || $dataarray['empinfo']['kriteriaPlt'] == 2) {
                        if ($dataarray['dipisah'] == 2) {
                            $showhplt = 1;
                            $showhunkir = 0;
                        }
                        if ($dataarray['dipisah'] == 1) {
                            $showhplt = 0;
                            $showhunkir = 1;
                        }
                        if ($dataarray['dipisah'] == 0) {
                            $showhplt = 1;
                            $showhunkir = 1;
                        }
                    }

                    if ($dataarray['empinfo']['kriteriaPlt'] == 3) {
                        $showhplt = 1;
                        $showhunkir = 0;
                    }
                    foreach ($dataarray['data'] as $row) 
                    {
                        $nPlt = 0;
                        $nUnkir = 0;
                        $nTotalRow = 0;
                        $showplt = 0;
                        $showunkir = 1;
                        $nUnkir = ceil(round($row['total'], 2));
                        $nTotalRow = ceil(round($row['total'], 2)) + ceil(round($row['totalplt'], 2));
                        if ($dataarray['empinfo']['kriteriaPlt'] != 3) {
                            if ($dataarray['empinfo']['kriteriaPlt'] == 1 || $dataarray['empinfo']['kriteriaPlt'] == 2) {
                                $nPlt = ceil(round($row['totalplt'], 2));
                                if ($dataarray['dipisah'] == 2) {
                                    $showplt = 1;
                                    $showunkir = 0;
                                    $nTotalRow = ceil(round($row['totalplt'], 2));
                                }
                                if ($dataarray['dipisah'] == 0) {
                                    $showplt = 1;
                                    $showunkir = 1;
                                    $nTotalRow = ceil(round($row['total'], 2)) + ceil(round($row['totalplt'], 2));
                                }
                                if ($dataarray['dipisah'] == 1) {
                                    $showplt = 0;
                                    $showunkir = 1;
                                    $nTotalRow = ceil(round($row['total'], 2));
                                }
                            }
                        } else {
                            $nPlt = ceil(round($row['totalplt'], 2));
                            $nUnkir = 0;
                            $showplt = 1;
                            $showunkir = 0;
                            $nTotalRow = ceil(round($row['totalplt'], 2));
                        }

                        $njml = $nTotalRow;
                        if ($showplt == 1 || $dataarray['byuser'] == 1) 
                        { 
                                $njml = $nPlt;
                        }
                        if ($showunkir == 1 || $dataarray['byuser'] == 1) { 
                                $njml= $nUnkir;
                        } 
                        //$njml = $nTotalRow;

                        $dataresult['data'][] = array(
                            'tgl'=>$row['date'],
                            'status'=>$row['status'],
                            'nilai'=>$row['nilai'],
                            'persentase'=>$row['pengurangan'],
                            'jumlah'=>$njml,
                        );
                    } 
                }
                else { 
                        foreach ($dataarray['data'] as $row) {
                            $dataresult['data'][] = array(
                                'tgl'=>$row['date'],
                                'status'=>$row['status'],
                                'nilai'=>$row['nilai'],
                                'persentase'=>$row['pengurangan'],
                                'jumlah'=>ceil(round($row['total'], 2)),
                            );
                        }
                }
            }
        } 
        if (!isset($dataresult['data']))
        {
            $dataresult['data']=array();
        }
        return $dataresult;
    }
}
